# Generated by Django 4.0.3 on 2022-03-08 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supportdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
